### ISSUE TITLE
Web process failed to bind to $PORT on Heroku

### ISSUE THREAD

**Issue by ganey** [scottrobertson/monzo-to-ynab#13] opened 2017-04-26 12:59 UTC
I'm getting this port bind error when deploying to Heroku. 

Previously I was just updating a manual heroku deploy, but also getting this error when using the readme Heroku deploy button.

```
-- previous log stuff --
app[web.1]: DEBUG:requests.packages.urllib3.connectionpool:https://app.youneedabudget.com:443 "POST /api/v1/catalog HTTP/1.1" 200 None
app[web.1]: DEBUG:pynYNAB.ObjClient:server_knowledge_of_device 0
app[web.1]: DEBUG:pynYNAB.ObjClient:current_server_knowledge 6989
app[web.1]: DEBUG:pynYNAB.ObjClient:Server knowledge has gone up by 6989. We should be getting back some entities from the server
app[web.1]: DEBUG:pynYNAB.ObjClient:current_device_knowledge 0
app[web.1]: DEBUG:pynYNAB.ObjClient:device_knowledge_of_server 6989
app[web.1]: INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app[web.1]: DEBUG:settings:assigning accounts and payees
heroku[web.1]: State changed from starting to crashed
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
heroku[web.1]: Stopping process with SIGKILL
heroku[web.1]: Process exited with status 137
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
app[web.1]: DEBUG:pynYNAB.ObjClient:server_knowledge_of_device 0
app[web.1]: DEBUG:pynYNAB.ObjClient:current_server_knowledge 6989
app[web.1]: DEBUG:pynYNAB.ObjClient:Server knowledge has gone up by 6989. We should be getting back some entities from the server
app[web.1]: DEBUG:pynYNAB.ObjClient:current_device_knowledge 0
app[web.1]: DEBUG:pynYNAB.ObjClient:device_knowledge_of_server 6989
app[web.1]: INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app[web.1]: DEBUG:settings:assigning accounts and payees
heroku[web.1]: State changed from starting to crashed
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
heroku[web.1]: Stopping process with SIGKILL
heroku[web.1]: Process exited with status 137
-- continuously loops through server knowledge and crash --
```

**Comment by scottrobertson** [comment] 2017-04-26 13:03
@ganey how many transactions do you have in YNAB out of interest?

**Comment by ganey** [comment] 2017-04-26 13:09
1027, my budget only goes back as far as 09/Sept/2016 

My Monzo account in YNAB has around 120 transactions

I have 14 'Budget' Accounts , 1 Tracking/Savings account and 4 'Closed' accounts setup in YNAB if they make any difference at all.

**Comment by ganey** [comment] 2017-04-26 13:20
It's not happy with os in main.py, does it need an `import os` or something in main.py?

```
2017-04-26T13:16:01.073611+00:00 app[web.1]: DEBUG:settings:assigning accounts and payees
2017-04-26T13:16:01.077217+00:00 app[web.1]: Traceback (most recent call last):
2017-04-26T13:16:01.077219+00:00 app[web.1]:   File "python/main.py", line 137, in <module>
2017-04-26T13:16:01.077283+00:00 app[web.1]:     port = int(os.environ.get("PORT", 5000))
2017-04-26T13:16:01.077303+00:00 app[web.1]: NameError: name 'os' is not defined
2017-04-26T13:16:01.233591+00:00 heroku[web.1]: Process exited with status 1
2017-04-26T13:16:01.220638+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by scottrobertson** [comment] 2017-04-26 13:24
Oh woops sorry. Pushed a fix.

So the problem is, heroku only gives us 60 seconds to boot, and we sync with YNAB on boot.

**Comment by ganey** [comment] 2017-04-26 13:38
Thanks!

It seems to be booting okay now `heroku[web.1]: State changed from starting to up`

Not sure how long the sync takes overall though.

**Comment by scottrobertson** [comment] 2017-04-26 14:24
To be honest, i think we are going to just have to introduce optional background jobs. That way we can handle all of the syncing in a background process for larger accounts and it doesnt matter how slow the sync is

**Closed** 2017-04-26 15:45 UTC
